### ISSUE TITLE
Interrupt interval 2X requested interval

### ISSUE THREAD

**Issue by wcwuttke** [khoih-prog/megaAVR_TimerInterrupt#1]
Arduino IDE version 1.8.13
Adruino WiFI Rev 2
OS: Win 10
  
Context:
Actual interrupt delay is 2 times the programmed value. e.g., programmed value = 10 ms., actual value = 20 ms.

Steps to reproduce:
1. Compile and run the Argument_None example with: #define TIMER1_INTERVAL_MS    11L, adding pin A0 to the
toggle1 code to observe the output on an oscilloscope connected to pin A0.
2. Observe that the waveform toggles at twice the programmed value (22 ms).

Works the same with any clock selected.

Am I doing something wrong?

```
/****************************************************************************************************************************
  Argument_None.ino
  For Arduino megaAVR ATMEGA4809-based boards (UNO WiFi Rev2, NANO_EVERY, etc. )
  Written by Khoi Hoang

  Built by Khoi Hoang https://github.com/khoih-prog/megaAVR_TimerInterrupt
  Licensed under MIT license

  Now with we can use these new 16 ISR-based timers, while consuming only 1 hwarware Timer.
  Their independently-selected, maximum interval is practically unlimited (limited only by unsigned long miliseconds)
  The accuracy is nearly perfect compared to software timers. The most important feature is they're ISR-based timers
  Therefore, their executions are not blocked by bad-behaving functions / tasks.
  This important feature is absolutely necessary for mission-critical tasks.

  Version: 1.3.0

  Version Modified By   Date      Comments
  ------- -----------  ---------- -----------
  1.0.0   K.Hoang      01/04/2021 Initial coding to support Arduino megaAVR ATmega4809-based boards (UNO WiFi Rev2, etc.)
  1.1.0   K.Hoang      14/04/2021 Fix bug. Don't use v1.0.0
  1.2.0   K.Hoang      17/04/2021 Selectable TCB Clock 16MHz, 8MHz or 250KHz depending on necessary accuracy
  1.3.0   K.Hoang      17/04/2021 Fix TCB Clock bug. Don't use v1.2.0
 *****************************************************************************************************************************/

// These define's must be placed at the beginning before #include "megaAVR_TimerInterrupt.h"
// _TIMERINTERRUPT_LOGLEVEL_ from 0 to 4
// Don't define _TIMERINTERRUPT_LOGLEVEL_ > 0. Only for special ISR debugging only. Can hang the system.
#define TIMER_INTERRUPT_DEBUG         0
#define _TIMERINTERRUPT_LOGLEVEL_     0

// Select USING_16MHZ     == true for  16MHz to Timer TCBx => shorter timer, but better accuracy
// Select USING_8MHZ      == true for   8MHz to Timer TCBx => shorter timer, but better accuracy
// Select USING_250KHZ    == true for 250KHz to Timer TCBx => shorter timer, but better accuracy
// Not select for default 250KHz to Timer TCBx => longer timer,  but worse accuracy
#define USING_16MHZ     false
#define USING_8MHZ      false
#define USING_250KHZ    true

#define USE_TIMER_0     false
#define USE_TIMER_1     true
#define USE_TIMER_2     false
#define USE_TIMER_3     false

#include "megaAVR_TimerInterrupt.h"

#define TIMER1_INTERVAL_MS    11L

#ifndef LED_BUILTIN
  #define LED_BUILTIN   13
#endif

void TimerHandler1(void)
{
  static bool toggle1 = false;
  static bool started = false;

  if (!started)
  {
    started = true;
    pinMode(LED_BUILTIN, OUTPUT);
    pinMode(A0, OUTPUT);
  }

  //timer interrupt toggles pin LED_BUILTIN
  digitalWrite(LED_BUILTIN, toggle1);
  digitalWrite(A0, toggle1);
  toggle1 = !toggle1;
}

#if USE_TIMER_2

#define TIMER2_INTERVAL_MS    2

void TimerHandler2(void)
{
  static bool toggle2 = false;
  static bool started = false;

  if (!started)
  {
    started = true;
    pinMode(A0, OUTPUT);
  }

  //timer interrupt toggles outputPin
  digitalWrite(A0, toggle2);
  toggle2 = !toggle2;
}
#endif

void setup()
{
  Serial.begin(115200);
  while (!Serial);

  Serial.print(F("\nStarting Argument_None on "));
  Serial.println(BOARD_NAME);
  Serial.println(MEGA_AVR_TIMER_INTERRUPT_VERSION);
  Serial.print(F("CPU Frequency = ")); Serial.print(F_CPU / 1000000); Serial.println(F(" MHz"));

  Serial.print(F("TCB Clock Frequency = ")); 

#if USING_16MHZ  
  Serial.println(F("16MHz for highest accuracy"));
#elif USING_8MHZ  
  Serial.println(F("8MHz for very high accuracy"));
#else
  Serial.println(F("250KHz for lower accuracy but longer time"));
#endif

  // Select Timer 1-2 for UNO, 0-5 for MEGA
  // Timer 2 is 8-bit timer, only for higher frequency
  ITimer1.init();

  // Using ATmega328 used in UNO => 16MHz CPU clock ,
  // For 16-bit timer 1, 3, 4 and 5, set frequency from 0.2385 to some KHz
  // For 8-bit timer 2 (prescaler up to 1024, set frequency from 61.5Hz to some KHz

  if (ITimer1.attachInterruptInterval(TIMER1_INTERVAL_MS, TimerHandler1))
  {
    Serial.print(F("Starting  ITimer1 OK, millis() = ")); Serial.println(millis());
  }
  else
    Serial.println(F("Can't set ITimer1. Select another freq. or timer"));

#if USE_TIMER_2

  // Select Timer 1-2 for UNO, 0-5 for MEGA
  // Timer 2 is 8-bit timer, only for higher frequency
  ITimer2.init();

  if (ITimer2.attachInterruptInterval(TIMER2_INTERVAL_MS, TimerHandler2))
  {
    Serial.print(F("Starting  ITimer2 OK, millis() = ")); Serial.println(millis());
  }
  else
    Serial.println(F("Can't set ITimer2. Select another freq. or timer"));
    
#endif
}

void loop()
{

}
```

**Comment by khoih-prog** [comment]
Hi @wcwuttke 

Thanks for your interests in the library.

1. I think you have to use **16MHz** clock to Timers for better accuracy

```
// Select USING_16MHZ     == true for  16MHz to Timer TCBx => shorter timer, but better accuracy
// Select USING_8MHZ      == true for   8MHz to Timer TCBx => shorter timer, but better accuracy
// Select USING_250KHZ    == true for 250KHz to Timer TCBx => shorter timer, but better accuracy
// Not select for default 250KHz to Timer TCBx => longer timer,  but worse accuracy
#define USING_16MHZ     true
#define USING_8MHZ      false
#define USING_250KHZ    false
```

also megaAVR is a very slow MCU, doing to many things within `10ms`, such as 

```
//timer interrupt toggles pin LED_BUILTIN
digitalWrite(LED_BUILTIN, toggle1);
digitalWrite(A0, toggle1);
```

possibly distorts its timings.

2. Try this example [**ISR_16_Timers_Array_Complex**](https://github.com/khoih-prog/megaAVR_TimerInterrupt/tree/main/examples/ISR_16_Timers_Array_Complex).

The best way to know the timings is correct is to use a **counter inside the ISR,** then print it out using a timing loop outside ISR, using millis().

For example, you can see the timing is very accurate here

```
Starting ISR_16_Timers_Array_Complex on megaAVR Nano Every
megaAVR_TimerInterrupt v1.3.0
CPU Frequency = 16 MHz
TCB Clock Frequency = 16MHz for highest accuracy
[TISR] TCB 1
[TISR] ==================
[TISR] Init, Timer = 1
[TISR] CTRLB   = 0
[TISR] CCMP    = 65535
[TISR] INTCTRL = 0
[TISR] CTRLA   = 1
[TISR] ==================
[TISR] Frequency = 200.00 , CLK_TCB_FREQ = 16000000
[TISR] setFrequency: _CCMPValueRemaining =  80000
[TISR] ==================
[TISR] set_CCMP, Timer = 1
[TISR] CTRLB   = 0
[TISR] CCMP    = 65535
[TISR] INTCTRL = 1
[TISR] CTRLA   = 1
Starting  ITimer1 OK, millis() = 13
SimpleTimer : 2, ms : 10013, Dms : 10013
Timer : 0, programmed : 5000, actual : 5015
Timer : 1, programmed : 10000, actual : 0
Timer : 2, programmed : 15000, actual : 0
Timer : 3, programmed : 20000, actual : 0
Timer : 4, programmed : 25000, actual : 0
Timer : 5, programmed : 30000, actual : 0
Timer : 6, programmed : 35000, actual : 0
Timer : 7, programmed : 40000, actual : 0
Timer : 8, programmed : 45000, actual : 0
Timer : 9, programmed : 50000, actual : 0
Timer : 10, programmed : 55000, actual : 0
Timer : 11, programmed : 60000, actual : 0
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 20072, Dms : 10059
Timer : 0, programmed : 5000, actual : 4998
Timer : 1, programmed : 10000, actual : 9995
Timer : 2, programmed : 15000, actual : 15017
Timer : 3, programmed : 20000, actual : 20015
Timer : 4, programmed : 25000, actual : 0
Timer : 5, programmed : 30000, actual : 0
Timer : 6, programmed : 35000, actual : 0
Timer : 7, programmed : 40000, actual : 0
Timer : 8, programmed : 45000, actual : 0
Timer : 9, programmed : 50000, actual : 0
Timer : 10, programmed : 55000, actual : 0
Timer : 11, programmed : 60000, actual : 0
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 30131, Dms : 10059
Timer : 0, programmed : 5000, actual : 4997
Timer : 1, programmed : 10000, actual : 10002
Timer : 2, programmed : 15000, actual : 15000
Timer : 3, programmed : 20000, actual : 20015
Timer : 4, programmed : 25000, actual : 25020
Timer : 5, programmed : 30000, actual : 30017
Timer : 6, programmed : 35000, actual : 0
Timer : 7, programmed : 40000, actual : 0
Timer : 8, programmed : 45000, actual : 0
Timer : 9, programmed : 50000, actual : 0
Timer : 10, programmed : 55000, actual : 0
Timer : 11, programmed : 60000, actual : 0
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 40192, Dms : 10061
Timer : 0, programmed : 5000, actual : 5005
Timer : 1, programmed : 10000, actual : 10002
Timer : 2, programmed : 15000, actual : 15000
Timer : 3, programmed : 20000, actual : 20004
Timer : 4, programmed : 25000, actual : 25020
Timer : 5, programmed : 30000, actual : 30017
Timer : 6, programmed : 35000, actual : 35014
Timer : 7, programmed : 40000, actual : 40019
Timer : 8, programmed : 45000, actual : 0
Timer : 9, programmed : 50000, actual : 0
Timer : 10, programmed : 55000, actual : 0
Timer : 11, programmed : 60000, actual : 0
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 50252, Dms : 10060
Timer : 0, programmed : 5000, actual : 4997
Timer : 1, programmed : 10000, actual : 9995
Timer : 2, programmed : 15000, actual : 15000
Timer : 3, programmed : 20000, actual : 20004
Timer : 4, programmed : 25000, actual : 24994
Timer : 5, programmed : 30000, actual : 30017
Timer : 6, programmed : 35000, actual : 35014
Timer : 7, programmed : 40000, actual : 40019
Timer : 8, programmed : 45000, actual : 45017
Timer : 9, programmed : 50000, actual : 50014
Timer : 10, programmed : 55000, actual : 0
Timer : 11, programmed : 60000, actual : 0
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 60314, Dms : 10062
Timer : 0, programmed : 5000, actual : 4997
Timer : 1, programmed : 10000, actual : 10002
Timer : 2, programmed : 15000, actual : 14999
Timer : 3, programmed : 20000, actual : 19997
Timer : 4, programmed : 25000, actual : 24994
Timer : 5, programmed : 30000, actual : 29999
Timer : 6, programmed : 35000, actual : 35014
Timer : 7, programmed : 40000, actual : 40019
Timer : 8, programmed : 45000, actual : 45017
Timer : 9, programmed : 50000, actual : 50014
Timer : 10, programmed : 55000, actual : 55019
Timer : 11, programmed : 60000, actual : 60016
Timer : 12, programmed : 65000, actual : 0
Timer : 13, programmed : 70000, actual : 0
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 70376, Dms : 10062
Timer : 0, programmed : 5000, actual : 5006
Timer : 1, programmed : 10000, actual : 10003
Timer : 2, programmed : 15000, actual : 14999
Timer : 3, programmed : 20000, actual : 19997
Timer : 4, programmed : 25000, actual : 24994
Timer : 5, programmed : 30000, actual : 29999
Timer : 6, programmed : 35000, actual : 35005
Timer : 7, programmed : 40000, actual : 40019
Timer : 8, programmed : 45000, actual : 45017
Timer : 9, programmed : 50000, actual : 50014
Timer : 10, programmed : 55000, actual : 55019
Timer : 11, programmed : 60000, actual : 60016
Timer : 12, programmed : 65000, actual : 65013
Timer : 13, programmed : 70000, actual : 70019
Timer : 14, programmed : 75000, actual : 0
Timer : 15, programmed : 80000, actual : 0
SimpleTimer : 2, ms : 80439, Dms : 10063
Timer : 0, programmed : 5000, actual : 4997
Timer : 1, programmed : 10000, actual : 9994
Timer : 2, programmed : 15000, actual : 15000
Timer : 3, programmed : 20000, actual : 19997
Timer : 4, programmed : 25000, actual : 25002
Timer : 5, programmed : 30000, actual : 29999
Timer : 6, programmed : 35000, actual : 35005
Timer : 7, programmed : 40000, actual : 39994
Timer : 8, programmed : 45000, actual : 45017
Timer : 9, programmed : 50000, actual : 50014
Timer : 10, programmed : 55000, actual : 55019
Timer : 11, programmed : 60000, actual : 60016
Timer : 12, programmed : 65000, actual : 65013
Timer : 13, programmed : 70000, actual : 70019
Timer : 14, programmed : 75000, actual : 75016
Timer : 15, programmed : 80000, actual : 80013
```

Good Luck,

**Comment by wcwuttke** [comment]
Hello,

I need a 1 millisecond timer. That can only be done with the 250 KHz clock.
According to the formula, the correct value gets stored in TCB1_CCMP
(250) for a 1 ms timer. However, the timer interval is 2 ms. I made a workaround
by changing TCB1_CCMP in my code. Now I have interrupts occurring at
precise 1 ms intervals (as measured with my oscilloscope). It behaves as if the
250 KHz clock has been divided by two somewhere.

Bill Wuttke

**Comment by khoih-prog** [comment]
Good to know it's OK for you.

> It behaves as if the 250 KHz clock has been divided by two somewhere.

I actually haven't tested with 250KHz. Possibly a bug somewhere in this library, or the core???

I'll spend some time to investigate later whenever I have time. I'd appreciate it you could help here to locate the issue.

Regards,

**Comment by wcwuttke** [comment]
Hello Khoi,

I'll be investigating further tomorrow. It's been a long time since I've played around with registers, etc.,
and then it was on 6800 & Z80s. Things have changed alot since then. Anyhow, I'll try to do
some register manipulation to get a basic timer going so I can do a comparison. I'll let
you know what I find.

Regards,
Bil Wuttke
     On Sunday, September 5, 2021, 07:09:51 PM PDT, Khoi Hoang ***@***.***> wrote:  
 
 


Good to know it's OK for you.


It behaves as if the 250 KHz clock has been divided by two somewhere.


I actually haven't tested with 250KHz. Possibly a bug somewhere in this library, or the core???

I'll spend some time to investigate later whenever I have time. I'd appreciate it you could help here to locate the issue.

Regards,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wcwuttke** [comment]
Hello Khoi,

I wrote two test sketches today, one for TCA, and one for TCB, using direct register manipulation.
Both work correctly, delivering 1 millisecond interrupts using sys_clk/64. Both are attached.
(Although the TCB timing is a little "glitchy" on the oscilloscope.) The TCB code probably
has an error or two.

Regards,
Bill Wuttke

//**************************************************************************************************
//**************************************************************************************************

// TCA Timer Test Sketch. 1 millisecond timer.
// modified from Microchip TB3217 example 7-1

#define PERIOD_EXAMPLE_VALUE (249) /* 1 millisecond using sys_clk/64 */

void TCA0_init(void)
{
 /* enable overflow interrupt */
 TCA0.SINGLE.INTCTRL = TCA_SINGLE_OVF_bm;
 
 /* set Normal mode */
 TCA0.SINGLE.CTRLB = TCA_SINGLE_WGMODE_NORMAL_gc;
 
 /* disable event counting */
 TCA0.SINGLE.EVCTRL &= ~(TCA_SINGLE_CNTEI_bm);
 
 /* set the period */
 TCA0.SINGLE.PER = PERIOD_EXAMPLE_VALUE; 
 
 TCA0.SINGLE.CTRLA = TCA_SINGLE_CLKSEL_DIV64_gc /* set clock source (sys_clk/64) */
 | TCA_SINGLE_ENABLE_bm; /* start timer */
}
void PORT_init(void)
{
 /* set pin 0 of PORT A as output */
 pinMode(A0, OUTPUT);
}

ISR(TCA0_OVF_vect)
{
 static bool toggle1 = false;
 /* Toggle PIN 0 of PORT A */
 digitalWrite(A0, toggle1);
 toggle1 = !toggle1;
 /* The interrupt flag has to be cleared manually */
 TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;
}

void setup() {
 PORT_init();
 TCA0_init();
 /* enable global interrupts */
 sei();
}

void loop() {

}

//**************************************************************************************************
//**************************************************************************************************

// TCB Timer Test Sketch. 1 millisecond timer.

#define PERIOD_EXAMPLE_VALUE (250) /* 1 millisecond using sys_clk/64 */

void CLOCK_init (void)
{
 /* Enable writing to protected register */
 CPU_CCP = CCP_IOREG_gc;
 /* Enable Prescaler and set Prescaler Division to 64 */
 CLKCTRL.MCLKCTRLB = CLKCTRL_PDIV_64X_gc | CLKCTRL_PEN_bm;
 
 /* Enable writing to protected register */
 CPU_CCP = CCP_IOREG_gc;
 /* Select OSC20M */
 CLKCTRL.MCLKCTRLA = CLKCTRL_CLKSEL_OSC20M_gc;
 
 /* Wait for system oscillator changing to finish */
 while (CLKCTRL.MCLKSTATUS & CLKCTRL_SOSC_bm)
 {
 ;
 }
}

void TCB1_init(void)
{
 /* Load the Compare or Capture register with the timeout value*/
 TCB1.CCMPL = PERIOD_EXAMPLE_VALUE;
 TCB1.CCMPH = 0;
 
 /* Enable TCB and set CLK_PER divider to 1 (No Prescaling) */
 TCB1.CTRLA = TCB_CLKSEL_CLKDIV1_gc | TCB_ENABLE_bm;
 
 /* Configure TCB in Periodic Timeout mode */
 TCB1.CTRLB = TCB_CCMPEN_bm;
 
 /* Enable Capture or Timeout interrupt */
 TCB1.INTCTRL = TCB_CAPT_bm;
}

void PORT_init (void)
{
 /* set pin 0 of PORT A as output */
 pinMode(A0, OUTPUT);
}

ISR(TCB1_INT_vect)
{
 static bool toggle1 = false;
 /* Toggle PIN 0 of PORT A */
 digitalWrite(A0, toggle1);
 toggle1 = !toggle1;
 /* The interrupt flag has to be cleared manually */
 TCB1.INTFLAGS = TCB_CAPT_bm; /* Clear the interrupt flag */
}

void setup() {
 CLOCK_init();
 PORT_init();
 TCB1_init();

 sei();
}

void loop() {

}
     On Sunday, September 5, 2021, 07:09:51 PM PDT, Khoi Hoang ***@***.***> wrote:  
 
 


Good to know it's OK for you.


It behaves as if the 250 KHz clock has been divided by two somewhere.


I actually haven't tested with 250KHz. Possibly a bug somewhere in this library, or the core???

I'll spend some time to investigate later whenever I have time. I'd appreciate it you could help here to locate the issue.

Regards,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by khoih-prog** [comment]
Thanks Bill,

> The TCB code probably has an error or two.

Do you mean error in the library? I believe so.. Could you please help locate and make a PR ?
If not possible due to time constraint, it's OK and I understand and will fix it later.

I'm reopening the issue now

Best Regards,

Khoi

**Comment by wcwuttke** [comment]
Hello Khoi,

I've been trying to locate the problem - it looks like you set the timer registers correctly.
It looks like you are not using the interrupt directly, but do something with counts - that's
where I get lost.

I am totally unfamiliar with the workings of Github, except that it stores one of my projects.
Therefore, I'll leave the PR, etc, for you.

My immediate problem (need for 1 ms timer) has been solved by using a few lines of code to
set the timer registers.

Best Regards,
Bill Wuttke


     On Monday, September 6, 2021, 01:51:10 PM PDT, Khoi Hoang ***@***.***> wrote:  
 
 


Thanks Bill,


The TCB code probably has an error or two.


Do you mean error in the library? I believe so.. Could you please help locate and make a PR ?
If not possible due to time constraint, it's OK and I understand and will fix it later.

I'm reopening the issue now

Best Regards,

Khoi

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by khoih-prog** [comment]
Hi Bill,

Thanks. I'll spend some time later to investigate, locate and solve this issue.

Regards,

**Comment by khoih-prog** [comment]
Hi @wcwuttke 

I'm sorry to wait too long to fix the bug, which is `delicate and hard-to-find` and happened only to high frequencies (around >245Hz). The bug has just been fixed by the new [**megaAVR_TimerInterrupt releases v1.4.0**](https://github.com/khoih-prog/megaAVR_TimerInterrupt/releases/tag/v1.4.0)

Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/megaAVR_TimerInterrupt#contributions-and-thanks)

Regards,

---

### Release v1.4.0

1. Fix TCB Clock bug in high frequencies. Check [Interrupt interval 2X requested interval #1](https://github.com/khoih-prog/megaAVR_TimerInterrupt/issues/1)
2. Add example to demo High Frequency
3. Delete Blynk-related examples
4. Add changelog.md
