### ISSUE TITLE
Platformio installation

### ISSUE THREAD

**Issue by n1coh** [khoih-prog/megaAVR_TimerInterrupt#2]
Hi, thanks for this easy to use library.

I can't install it via platformio, I have this error:

`Error: VCS: Unknown repository type khoih.prog@gmail.com/megaAVR_TimerInterrupt`

I think it's bad platformio config.

**Comment by khoih-prog** [comment]
You have to use `khoih-prog/megaAVR_TimerInterrupt`, not `khoih.prog@gmail.com/megaAVR_TimerInterrupt`

@ivankravets

Could you please check why all the installation instructions now changes to `khoih.prog@gmail.com/library_name`, not `khoih-prog/library_name` anymore. Thanks.

![Selection_065](https://user-images.githubusercontent.com/57012152/137592724-753b7837-ad95-4909-a50c-7eddc0cea137.png)

**Comment by ivankravets** [comment]
@khoih-prog Sorry for the issue. I can't understand what is going with your account. The only I remove duplicated account, someone creates a new one. I've just removed again duplicated account.

So, let's re-test the system. Could you try to log in with a Github account to PlatformIO? Maybe, we have a problem with our account system. See details below for the account.

![Screen Shot 2021-10-16 at 19 03 26](https://user-images.githubusercontent.com/1760209/137594297-a907b399-539b-4c61-9078-e6b80f31473e.png)
m.

**Comment by khoih-prog** [comment]
@ivankravets 

I just login again and change the password, in case the account was hacked somehow.

Is there any change in your system recently, as some days ago, I checked and still saw installation instructions as

```
pio lib install "khoih-prog/megaAVR_TimerInterrupt"
```

**Comment by ivankravets** [comment]
> pio lib install "khoih-prog/megaAVR_TimerInterrupt"

This is the correct installation command. See https://platformio.org/lib/show/12025/megaAVR_TimerInterrupt/installation

> I just login again and change the password, in case the account was hacked somehow.

Great! Next time please use `pio lib publish --owner khoih-prog /path/to/lib`

> I login using in Ubuntu Terminal

What is your `pio --version`?

**Comment by ivankravets** [comment]
Super! Please contact me anytime when you have any issues with our registry. 

Have a great weekend!

**Comment by khoih-prog** [comment]
Did you know why there are duplication of same library now?


![Selection_066](https://user-images.githubusercontent.com/57012152/137595696-d35a40e7-18d6-4d03-8cdc-1d369db10d04.png)

**Comment by khoih-prog** [comment]
> Great! Next time please use `pio lib publish --owner khoih-prog /path/to/lib`

Thanks. For the record, I think the correct command is

```
`pio package publish --owner khoih-prog /path/to/lib`
```
