### ISSUE TITLE
Warning on _prescalerIndex not initialized

### ISSUE THREAD

**Issue by pischky** [khoih-prog/megaAVR_TimerInterrupt#3]
eclipse (sloeber 4.4.0) shows two warnings:

```
Member '_prescalerIndex' was not initialized in this constructor 

megaAVR_TimerInterrupt.hpp

line 126	

Code Analysis Problem
```

Same in line 136

Version used 1.6.0 on Arduino Nano Every. Platform version 1.8.7.

Looks to me that _prescalerIndex is defined but never used. So I assume that this is no real problem.

**Comment by khoih-prog** [comment]
Hi @pischky 

Done in [**megaAVR_TimerInterrupt** releases v1.6.1](https://github.com/khoih-prog/megaAVR_TimerInterrupt/releases/tag/v1.6.1).

Thanks,

---

### Release v1.6.1

1. Suppress warnings when `_TIMERINTERRUPT_LOGLEVEL_` < 2
2. Remove unused `_prescalerIndex`
